# Generated by Django 4.0.7 on 2022-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_price_alter_album_name_alter_photo_album_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name', 'ji', 'dong')},
        ),
        migrations.AddField(
            model_name='album',
            name='dong',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='ji',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
