# Generated by Django 4.0.7 on 2022-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_album_options_album_dong_album_ji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='album',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='album',
            name='ji',
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='상품 상태'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='상품 가격'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='상품제목'),
        ),
    ]
