# Generated by Django 4.0.7 on 2022-09-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0009_alter_album_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region1', models.CharField(choices=[('충청남도', '충청남도'), ('전라남도', '전라남도'), ('강원도', '강원도'), ('인천광역시', '인천광역시'), ('세종특별자치시', '세종특별자치시'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('대구광역시', '대구광역시'), ('경상북도', '경상북도'), ('경기도', '경기도'), ('전라북도', '전라북도'), ('충청북도', '충청북도'), ('서울특별시', '서울특별시'), ('부산광역시', '부산광역시')], max_length=30, null=True, verbose_name='지역')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region2', models.CharField(max_length=30, null=True, verbose_name='동네')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('upload_dt',)},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='상품 설명'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='photo',
            name='region1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.region1', verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='photo',
            name='region2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.region2', verbose_name='동네'),
        ),
    ]
