# Generated by Django 4.0.7 on 2022-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_alter_region1_region1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region1',
            name='region1',
            field=models.CharField(choices=[('광주광역시', '광주광역시'), ('인천광역시', '인천광역시'), ('경상남도', '경상남도'), ('전라남도', '전라남도'), ('제주특별자치도', '제주특별자치도'), ('강원도', '강원도'), ('세종특별자치시', '세종특별자치시'), ('충청남도', '충청남도'), ('경기도', '경기도'), ('전라북도', '전라북도'), ('충청북도', '충청북도'), ('대전광역시', '대전광역시'), ('서울특별시', '서울특별시'), ('경상북도', '경상북도'), ('울산광역시', '울산광역시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시')], max_length=30, null=True, verbose_name='지역'),
        ),
    ]
